// Placeholder	Replace With
// yourdockerhubusername	Your Docker Hub username
// github-creds-id	Jenkins credential ID for GitHub
// dockerhub-creds-id	Jenkins credential ID for Docker Hub
// yourusername	Your GitHub username (or org)


pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yourdockerhubusername/messaging_app:latest"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', credentialsId: 'github-creds-id', url: 'https://github.com/Abeniyo/alx-backend-python.git'
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip3 install --upgrade pip'
                sh './venv/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest messaging_app --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f messaging_app/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
    }
}
